# Generated by Django 3.0.8 on 2020-09-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id_etf', models.TextField(primary_key=True, serialize=False)),
                ('ticker_etf', models.TextField(blank=True, null=True)),
                ('description_etf', models.TextField(blank=True, null=True)),
                ('assetclass_etf', models.TextField(blank=True, null=True)),
                ('aum_etf', models.TextField(blank=True, null=True)),
                ('category_etf', models.TextField(blank=True, null=True)),
                ('inceptiondate_etf', models.DateTimeField(blank=True, null=True)),
                ('brand_etf', models.TextField(blank=True, null=True)),
                ('legalstructure_etf', models.TextField(blank=True, null=True)),
                ('indextracked_etf', models.TextField(blank=True, null=True)),
                ('issuer_etf', models.TextField(blank=True, null=True)),
                ('markettype_etf', models.TextField(blank=True, null=True)),
                ('focus_etf', models.TextField(blank=True, null=True)),
                ('fund_etf', models.TextField(blank=True, null=True)),
                ('geography_etf', models.TextField(blank=True, null=True)),
                ('niche_etf', models.TextField(blank=True, null=True)),
                ('region_etf', models.TextField(blank=True, null=True)),
                ('visibility_etf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.AutoField(primary_key=True, serialize=False)),
                ('name_provider', models.CharField(max_length=255)),
                ('detail_provider', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id_price', models.AutoField(primary_key=True, serialize=False)),
                ('price_price', models.FloatField()),
                ('nav_price', models.FloatField()),
                ('bid_ask_price', models.FloatField()),
                ('premiun_price', models.FloatField()),
                ('ytd_price', models.FloatField()),
                ('expanses_price', models.FloatField()),
                ('earnings_price', models.FloatField()),
                ('book_price', models.FloatField()),
                ('date_price', models.DateTimeField()),
                ('etf_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Etf')),
            ],
        ),
        migrations.AddField(
            model_name='etf',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('name_comp', models.CharField(max_length=255)),
                ('identifier_comp', models.CharField(max_length=255)),
                ('weigth_comp', models.FloatField()),
                ('sector_comp', models.CharField(max_length=255)),
                ('shares_comp', models.FloatField()),
                ('etf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Etf')),
            ],
        ),
    ]
